### ISSUE TITLE
Camp IVA importació/exportació productes

### ISSUE THREAD

**Issue by joancortes** [jorix/Aixada#2]
En l'arxiu per defecte `local_config/config.php.sample.laCistella`, en l'apartat de configuració de la importació/exportació de productes, consta com a camp per definir l'IVA `iva_percent_type_id` enlloc de `iva_percent_id` que és el que es demana durant la importació. Línia 636.

**Comment by jorix** [comment]
> ... enlloc de `iva_percent_id`...

Oops, sí! Arreglat, gràcies
